---
- hosts: all
  gather_facts: yes
  connection: ssh
  vars_files:
    - vars.yaml
  vars_prompt:
    - name: github_token
      prompt: "Enter your github personal access token?"
      private: true
  tasks:
    - name: Check if ssh key is already present
      stat:
        path: "{{ key_path }}"
      register: key_stat_result

    - name: Generate SSH key for accessing GitHub
      command: "ssh-keygen -t rsa -f {{ key_path }} -N ''"
      when: not key_stat_result.stat.exists

    - name: Get key content
      command: "cat {{ key_path }}.pub"
      register: key_content

    - name: Check if known_host exists
      stat:
        path: "{{ known_hosts_path }}"
      register: known_hosts_stat

    - name: Create known_hosts if it doesn't exist
      file:
        path: "{{ known_hosts_path }}"
        state: touch
      when: not known_hosts_stat.stat.exists

    - name: Get the content of known hosts
      shell: "cat {{ known_hosts_path }} | grep {{ git_server_fqdn }}"
      register: host_stat
      failed_when: host_stat.rc > 1


    - name: Modify known hosts
      block:
      - name: Fetch GitHub public key
        command: "ssh-keyscan -T 10 {{ git_server_fqdn }}"
        register: keyscan

      - name: Add GitHub public key to ssh known_hosts
        lineinfile:
          path: "{{ known_hosts_path }}"
          create: yes
          line: "{{ item }}"
        with_items: '{{ keyscan.stdout_lines }}'
      when: host_stat.rc == 1

    - name: Add SSH public key to GitHub account
      ansible.builtin.uri:
        url: "https://api.{{ git_server_fqdn }}/repos/{{ github_account_id }}/{{ repo }}/keys"
        validate_certs: yes
        method: POST
        force_basic_auth: true
        body:
          title: "{{ key_title }}"
          key: "{{ key_content.stdout }}"
          read_only: true
        body_format: json
        headers:
          Accept: application/vnd.github+json
          X-GitHub-Api-Version: 2022-11-28
          Authorization: "Bearer {{ github_access_token }}"
        status_code:
        - 201
        - 422
      register: create_result

    - name: Configure SSH agent and clone repository
      block:
      - name: Remove old repository
        file:
          path: "{{ clone_dest }}"
          state: absent

      - name: Add SSH key to SSH agent
        shell: |
          eval $(ssh-agent -s)
          ssh-add {{ key_path }}

      - name: Clone the repository
        shell: |                                                                                                                                   
          GIT_SSH_COMMAND="ssh -i {{ key_path }} -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" {{ git_executable }} clone git@{{ git_server_fqdn }}:{{ github_account_id }}/{{ repo }}.git {{ clone_dest }}

      #- name: Switch branch
      #  shell: "{{ git_executable }} checkout {{ host_location }}"
      #  args:
      #    chdir: "{{ clone_dest }}"

      - name: Debug create_result
        debug:
          var=create_result.json

      - name: Delete SSH public key
        ansible.builtin.uri:
          url: "https://api.{{ git_server_fqdn }}/repos/{{ github_account_id }}/{{ repo }}/keys/{{ create_result.json.id }}"
          validate_certs: yes
          method: DELETE
          force_basic_auth: true
          headers:
            Accept: application/vnd.github+json
            X-GitHub-Api-Version: 2022-11-28
            Authorization: "Bearer {{ github_access_token }}"
          status_code:
            - 204
      
      - name: Copy config
        ansible.builtin.copy:
          dest: "/home/mic-713/Detector/config.ini"
          src: "host_files/{{ host_location }}/config.ini"
          owner: mic-713
          group: mic-713
          mode: "0640"
      
      - name: Replace secure server
        ansible.builtin.replace:
          path: /home/mic-713/Detector/config.ini
          regexp: ([^ ]*)https://server.com([^ \.]*)
          replace: '\1{{ upload_server }}\2'

      - name: Replace usernames
        ansible.builtin.replace:
          path: /home/mic-713/Detector/edge.py
          regexp: ([^ ]*)user([^ \.]*)
          replace: '\1{{ cam_user }}\2'

      - name: Replace pass
        ansible.builtin.replace:
          path: /home/mic-713/Detector/edge.py
          regexp: ([^ ]*)passwrd([^ \.]*)
          replace: '\1{{ cam_pass }}\2'

      - name: Copy json
        ansible.builtin.copy:
          dest: "/home/mic-713/Detector/"
          src: "{{ item }}"
          owner: mic-713
          group: mic-713
          mode: "0640"
        with_fileglob:
          - "host_files/{{ host_location }}/*.json"

      - name: Create Script File
        ansible.builtin.copy:
          dest: "/home/mic-713/detector.sh"
          content: |
              #!/bin/bash
              cd /home/mic-713/Detector
              python3 edge.py -c config.ini
          owner: mic-713
          group: mic-713
          mode: '0700'

      - name: Install pip req
        ansible.builtin.pip:
          name:
            - packaging
            - tqdm
            - seaborn

      - name: Create cronjob
        ansible.builtin.cron:
          name: "TTI Truck Detector"
          minute: "*/5"
          job: "/home/mic-713/detector.sh"


      always:
      - name: Kill the ssh-agent
        shell: export pid=`ps -A | grep ssh-agent | awk 'NR==1{print $1}' | cut -d' ' -f1`; kill $pid